micronaut:
  application:
    name: app
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: classpath:webapp
netty:
  default:
    allocator:
      max-order: 3
